# Supabase CLI Configuration
# AI dev note: Configuração para deploy de migrações e Edge Functions

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage", "realtime"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:5173/auth/callback"

[edge_runtime]
enabled = true
port = 54327

[analytics]
enabled = false

[functions]
verify_jwt = false 